# Generated by Django 6.0 on 2025-12-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_beltprogress_instructor'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beltprogress',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instructor'),
        ),
    ]
