# Generated by Django 6.0 on 2025-12-22 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('rank', models.CharField(choices=[('1dan', '1st Dan Black Belt'), ('2dan', '2nd Dan Black Belt'), ('3dan', '3rd Dan Black Belt'), ('4dan', '4th Dan Black Belt'), ('5dan', '5th Dan Black Belt'), ('6dan', '6th Dan Black Belt'), ('7dan', '7th Dan Black Belt'), ('8dan', '8th Dan Black Belt'), ('9dan', '9th Dan Black Belt'), ('10dan', '10th Dan Black Belt')], max_length=50)),
                ('bio', models.TextField()),
                ('short_bio', models.CharField(blank=True, help_text='Brief description for listings', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('certifications', models.TextField(blank=True, help_text='List certifications, one per line')),
                ('specialization', models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite'), ('both', 'Kata & Kumite'), ('kids', 'Kids Training'), ('competition', 'Competition')], default='both', max_length=20)),
                ('photo', models.ImageField(upload_to='instructors/')),
                ('video_intro_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text="Format: {'instagram': 'url', 'facebook': 'url', 'linkedin': 'url', 'twitter': 'url'}", null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True, help_text='Available for new students')),
                ('max_students', models.PositiveIntegerField(default=30, help_text='Maximum class capacity')),
                ('total_students', models.PositiveIntegerField(default=0, editable=False)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, editable=False, max_digits=3)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('competition', 'Competition Medal'), ('championship', 'Championship Title'), ('certification', 'Certification'), ('milestone', 'Milestone'), ('award', 'Award'), ('recognition', 'Recognition')], default='competition', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=200)),
                ('highlight_color', models.CharField(default='#FFCD00', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('external_link', models.URLField(blank=True, help_text='Link to news article or proof')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, help_text='Students who earned this achievement', related_name='achievements', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='core.instructor')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('belt_rank', models.CharField(blank=True, help_text='e.g., Green Belt, 2nd Dan', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('message', models.TextField()),
                ('title', models.CharField(blank=True, help_text='Short highlight quote', max_length=150)),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor being reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.instructor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='core.instructor')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('instructor', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='InstructorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_quality', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('technique', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('motivation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('pros', models.TextField(blank=True, help_text='What you liked')),
                ('cons', models.TextField(blank=True, help_text='What could be improved')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified student review')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.instructor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Review',
                'verbose_name_plural': 'Instructor Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('instructor', 'user')},
            },
        ),
    ]
