# Generated by Django 6.0 on 2025-12-22 09:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KarateClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Kids', 'Kids (5-12)'), ('Teens', 'Teens (13-17)'), ('Adults', 'Adults (18+)'), ('Private', 'Private Lessons')], max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Competition', 'Competition Team')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_students', models.PositiveIntegerField(default=20)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('free_trial_spots', models.PositiveIntegerField(default=5)),
                ('requirements', models.TextField(blank=True, help_text='What students need to bring')),
                ('what_youll_learn', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instructor')),
            ],
            options={
                'verbose_name': 'Karate Class',
                'verbose_name_plural': 'Karate Classes',
                'ordering': ['-featured', 'category', 'level'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(default='Main Dojo', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('karate_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.karateclass')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('karate_class', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('Free Trial', 'Free Trial'), ('Monthly', 'Monthly Subscription'), ('Drop-in', 'Drop-in Class')], default='Monthly', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending Payment'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Failed', 'Failed')], default='Unpaid', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('booking_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_attempts', models.PositiveIntegerField(default=0)),
                ('last_payment_attempt', models.DateTimeField(blank=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('attendance_date', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('payment_email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classschedule')),
                ('karate_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.karateclass')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(max_length=50)),
                ('status_code', models.CharField(blank=True, max_length=20, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='classes.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('karate_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='classes.karateclass')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('karate_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='classes.karateclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'karate_class')},
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='classes_boo_user_id_c20e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['karate_class', 'status'], name='classes_boo_karate__d4e242_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['transaction_id'], name='classes_boo_transac_537667_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='classes_boo_booking_79ce1b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status', 'expires_at'], name='classes_boo_payment_23a43f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together={('user', 'karate_class', 'schedule')},
        ),
    ]
