# Generated by Django 6.0 on 2025-12-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/%Y/%m/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('caption', models.TextField(blank=True, help_text='Short description', null=True)),
                ('photographer', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('event_date', models.DateField(blank=True, help_text='Date when photo was taken', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage and category pages')),
                ('is_public', models.BooleanField(default=True, help_text='Make visible to public')),
                ('display_order', models.IntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery.gallerycategory')),
            ],
            options={
                'ordering': ['-is_featured', '-display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('images', models.ManyToManyField(blank=True, related_name='tags', to='gallery.galleryimage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['-uploaded_at'], name='gallery_gal_uploade_12a514_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['is_featured', '-uploaded_at'], name='gallery_gal_is_feat_055e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['category', '-uploaded_at'], name='gallery_gal_categor_549a03_idx'),
        ),
    ]
